version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: scase-food-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DATA_BASE_PASSWORD}
      MYSQL_DATABASE: ${DATA_BASE_NAME}
      MYSQL_USER: ${DATA_BASE_USERNAME}
      MYSQL_PASSWORD: ${DATA_BASE_PASSWORD}
    ports:
      - "${DATA_BASE_PORT}:${DATA_BASE_PORT}"
    volumes:
      - mysql-data:/var/lib/mysql

  nats:
    image: nats
    container_name: scase-food-nats
    restart: always
    ports:
      - "4222:4222"

  gateway:
    build:
      context: .
      dockerfile: .\apps\gateway\Dockerfile
      target: development
    command: pnpm run start:dev gateway
    depends_on:
      - nats
      - mysql
    ports:
      - '${SERVER_PORT}:${SERVER_PORT}'
    volumes:
      - .:\usr\src\app

  food-microservice:
    build:
      context: .
      dockerfile: .\apps\food-microservice\Dockerfile
      target: ${NODE_ENV}
    command: pnpm run start:dev food-microservice
    depends_on:
      - nats
      - mysql
    volumes:
      - .:\usr\src\app

  notification-microservice:
    build:
      context: .
      dockerfile: .\apps\notification-microservice\Dockerfile
      target: ${NODE_ENV}
    command: pnpm run start:dev notification-microservice
    depends_on:
      - nats
      - mysql
    volumes:
      - .:\usr\src\app

  order-microservice:
    build:
      context: .
      dockerfile: .\apps\order-microservice\Dockerfile
      target: ${NODE_ENV}
    command: pnpm run start:dev order-microservice
    depends_on:
      - nats
      - mysql
    volumes:
      - .:\usr\src\app

  restaurant-microservice:
    build:
      context: .
      dockerfile: .\apps\restaurant-microservice\Dockerfile
      target: ${NODE_ENV}
    command: pnpm run start:dev restaurant-microservice
    depends_on:
      - nats
      - mysql
    volumes:
      - .:\usr\src\app

  user-microservice:
    build:
      context: .
      dockerfile: .\apps\user-microservice\Dockerfile
      target: ${NODE_ENV}
    command: pnpm run start:dev user-microservice
    depends_on:
      - nats
      - mysql
    volumes:
      - .:\usr\src\app

volumes:
  mysql-data: